variable "ami_id" {}
variable "root_volume_size" {}
variable "root_volume_type" {}
variable "customer" {}
variable "environment" {}
variable "private-subnet-id-1" {}
variable "private-subnet-id-2" {}
variable "public-subnet-id-1" {}
variable "public-subnet-id-2" {}
variable "keypair" {}
variable "instance-size" {}
variable "vpc-id" {}
variable "deployment-version" {}
